# Generated by Django 2.1.8 on 2019-09-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
