# Generated by Django 2.1.8 on 2019-09-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginUser', '0002_auto_20190904_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
