# Generated by Django 2.1.8 on 2019-09-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0003_auto_20190909_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='\\images'),
        ),
    ]
