# Generated by Django 2.1.8 on 2019-09-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0006_auto_20190909_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/seller/images'),
        ),
    ]
