# Generated by Django 2.1.8 on 2019-09-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0009_goodstype'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='picture',
            field=models.ImageField(default='', upload_to='static/seller/images'),
            preserve_default=False,
        ),
    ]
