# Generated by Django 2.1.8 on 2019-09-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0011_auto_20190909_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodstype',
            name='picture',
            field=models.ImageField(default='seller/images', upload_to='seller/images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goods',
            name='picture',
            field=models.ImageField(upload_to='seller/images'),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='seller/images'),
        ),
    ]
