# Generated by Django 2.1.8 on 2019-09-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0012_auto_20190910_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_pro_time',
            field=models.DateField(),
        ),
    ]
